<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB91bnqL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB91bnqL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB91bnqL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB91bnqL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB91bnqL\App_KernelDevDebugContainer([
    'container.build_hash' => 'B91bnqL',
    'container.build_id' => 'f6a996e8',
    'container.build_time' => 1610913954,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB91bnqL');
